# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "New android build for Online Pharmacy"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :android_beta_app do
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            testers: "naufalwwidyatama@gmail.com",
            release_notes: "Lots of amazing new features to test out!",
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end
end


