name: release-android-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Setup Fastlane
        working-directory: ./android  # <-- Make sure you have this
        run: bundle install
      - name: Run Fastlane
        working-directory: ./android  # <-- Make sure you have this
        run: bundle exec fastlane android_beta_app
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
